/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/Mountain.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Mountain.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Landscape.geometry} material={nodes.Landscape.material} />
    </group>
  )
}

useGLTF.preload('/Mountain.glb')
