/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/ExplodingBalls.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/ExplodingBalls.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="空物体" />
        <group name="空物体001" rotation={[0, 0.001, 0]} />
        <mesh name="球体" geometry={nodes.球体.geometry} material={nodes.球体.material} />
        <mesh name="球体001" geometry={nodes.球体001.geometry} material={nodes.球体001.material} />
        <mesh name="球体002" geometry={nodes.球体002.geometry} material={nodes.球体002.material} />
        <mesh name="环体" geometry={nodes.环体.geometry} material={nodes.环体.material} />
        <mesh name="球体003" geometry={nodes.球体003.geometry} material={nodes.球体003.material} />
        <mesh name="球体004" geometry={nodes.球体004.geometry} material={nodes.球体004.material} />
        <mesh name="球体005" geometry={nodes.球体005.geometry} material={nodes.球体005.material} />
        <mesh name="环体001" geometry={nodes.环体001.geometry} material={nodes.环体001.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/ExplodingBalls.glb')
