/*
 * @Descripttion: 
 * @version: 1.0
 * @Author: Hesin
 * @Date: 2024-10-02 17:45:10
 * @LastEditors: Hesin
 * @LastEditTime: 2024-10-02 18:45:03
 */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/flame.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/flame.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="棱角球003" geometry={nodes.棱角球003.geometry} material={nodes.棱角球003.material} />
        <mesh name="棱角球004" geometry={nodes.棱角球004.geometry} material={nodes.棱角球004.material} />
        <mesh name="棱角球005" geometry={nodes.棱角球005.geometry} material={nodes.棱角球005.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/flame.glb')
